
# Not so silly exercises


1. Write a function that counts the number of NAs in a vector.

In [9]:
import numpy as np
import pandas as pd
vector = np.array([2, 1, 3, np.NaN, 5, np.NaN, 8, 9, 12, np.NaN, 10])

In [12]:
def countNan(vector):
    count = np.isnan(vector).sum()
    return count

In [13]:
countNan(vector)

3

2. Apply this function to all cols of a dataframe or matrix.


In [17]:
df = pd.DataFrame({'age': [np.NaN, 6, np.NaN],
                   'born': [pd.NaT, pd.Timestamp('1939-05-27'),
                            pd.Timestamp('1940-04-25')],
                   'name': ['Alfred', 'Batman', ''],
                   'toy': [None, 'Batmobile', 'Joker']})

In [18]:
df

,age,born,name,toy
0,NaN,NaT,Alfred,None
1,6.0,1939-05-27,Batman,Batmobile
2,NaN,1940-04-25,,Joker


In [19]:
x = df.age
countNan(x)

2

3. Make a matrix of random integers. Find the number of elements greater than 4 in each col of this matrix.

In [21]:
matrix = np.array([[1,2,3],[4,5,6],[7,9,8]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 9, 8]])

In [25]:
print(np.shape(matrix)[0])

3


In [97]:
matrix = np.array([[1,2,3],[4,5,6],[7,9,8]])
def countGreaterThanFour(matrix):
    counter = 0
    for i in range(0, np.shape(matrix)[0]):
        for j in range(0, np.shape(matrix)[1]):
            if matrix[i][j] > 4:
                counter += 1
    return counter

In [98]:
countGreaterThanFour(matrix)

5

4. In the matrix above, find the sums of elements greater than 4 in each col of this matrix. Report these sums for each col!

In [99]:
#Greater than 4 columnwise
matrix = np.array([[1,2,3],[4,5,6],[7,9,8]])
def countGreaterThanFourPerColumn(matrix):
    counter = []
    for i in range(0, np.shape(matrix)[0]):
        count = 0
        for j in range(0, np.shape(matrix)[1]):
            if matrix[j][i] > 4:
                count += 1
        counter.append(count)
    return counter

In [100]:
countGreaterThanFourPerColumn(matrix)

[1, 2, 2]

5. Write a function that takes a matrix and two integers i and j and interchanges cols i and j.

In [106]:
matrix = np.array([[2, 5, 8],[1, 4, 7],[9, 6, 3]])
def interchange(matrix, c1, c2):
    col = []
    for i in range(0, np.shape(matrix)[1]):
        col.append(matrix[i][c1])
    for i in range(0, np.shape(matrix)[1]):
        matrix[i][c1] = matrix[i][c2]
    for i in range(0, np.shape(matrix)[1]):
        matrix[i][c2] = col[i]
    return matrix
interchange(matrix, 1, 2)

array([[2, 8, 5],
       [1, 7, 4],
       [9, 3, 6]])

In [108]:
matrix = np.array([[2, 5, 8],[1, 4, 7],[9, 6, 3]])
matrix

array([[2, 5, 8],
       [1, 4, 7],
       [9, 6, 3]])

6. Write a function that prints the sum of the diagonal elements of a matrix. The function should only work for square matrices! (Hint: use stop())

In [88]:
matrix = np.array([[2, 5, 8],[1, 4, 7],[9, 6, 3]])
def sumOfDiagonalElements(matrix):
    sum = 0
    if(np.shape(matrix)[0] == np.shape(matrix)[1]):
        for i in range(0, np.shape(matrix)[0]):
            for j in range(0, np.shape(matrix)[1]):
                if (i == j):
                    sum += matrix[i][j]
    else:
        print("Input a square matrix")
    return sum
sumOfDiagonalElements(matrix)

9

7. Write a function that accepts a string as an argument. The function should print a string that only contains words with more than 4 characters. (Hint: use string manipulation functions!)


In [90]:
str = "hello how are you? Today is Friday"
def wordsGreaterThanFour(str):
    strWords = str.split()
    output_str = []
    for i in range(0, len(strWords)):
        if (len(strWords[i]) > 4):
            output_str.append(strWords[i])
    string = " "
    return string.join(output_str)
wordsGreaterThanFour(str)

'hello Today Friday'

8. Write a function that takes two strings as arguments. It should then print a string which alternates words from the two input strings. Example: if the input strings are: “hello today is Friday” and “r is nice”, the output should be: “hello r today is is nice Friday” What will you do if the lengths of the strings don’t permit you to do this?

In [81]:
str1 = "hello today is Friday"
str2 = "r is nice"
def alternateWords(str1, str2):
    output_str = []
    str1words = str1.split()
    str2words = str2.split()
    for i in range(0, len(str1words)+len(str2words)):
        if(i%2 == 0):
            output_str.append(str1words[int(i/2)])
        else:
            output_str.append(str2words[int((i-1)/2)])
    str = " "
    return str.join(output_str)
alternateWords(str1, str2)

'hello r today is is nice Friday'